In [1]:
from sklearn.feature_selection import RFE

from sklearn.svm import SVR

import pandas as pd

import numpy as np

In [2]:
dataset=pd.read_csv('../python-ml-course/datasets/ads/Advertising.csv')
dataset.shape

(200, 4)

## 1- Conocer con que variables es mas optimo el modelo

In [3]:
all_variables=dataset[['TV','Radio','Newspaper']]

variable_deseada=dataset['Sales']

estimador=SVR(kernel='linear') 

selector=RFE(estimador,2,step=1) #El 2 representa el numero de variables que queremos para el modelo predictivo

selector=selector.fit(all_variables,variable_deseada)

In [4]:
selector.support_  #Variables que se escogieron en base a variables_predictoras

array([ True,  True, False])

In [5]:
from sklearn.feature_selection import RFECV

rfe=RFECV(estimador)
rfe.fit(all_variables,variable_deseada)
rfe.n_features_

2

## 2-Crear Segmentos de Training y Testing

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
var_predictoras=dataset[['TV','Radio']] #variables basadas en el selector.support_

variable_deseada=dataset['Sales']

In [8]:
x_train, x_test, y_train, y_test =train_test_split(var_predictoras,variable_deseada,test_size=.2)

## 3- Usar variables para crear modelo predictivo

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
lm=LinearRegression() #definir modelo

lm.fit(x_train,y_train) #realizas el ajuste o fase entrenamiento

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
lm.intercept_ #ordenada del origen

2.7607808965697807

In [12]:
lm.coef_ #coeficientes 

array([0.0457114 , 0.19235138])

$$y=a+bx$$

In [13]:
sales_predict=lm.intercept_ + lm.coef_[0] * dataset['TV'] + lm.coef_[1] * dataset['Radio']

#sales_predict

## 4-Prediccion

In [14]:
sales_predict_2=lm.predict(x_test)
sales_predict_2

array([20.83094547, 11.53822356,  7.52298707, 16.97428844, 21.70952763,
       21.11523765, 15.63049875, 24.82424958, 15.45153728,  6.42683502,
       11.43269657,  8.76537198, 13.10279659, 17.19145122,  8.0322284 ,
       21.2505961 , 15.25219741, 15.09275278, 10.59979855,  9.77223868,
        8.67951271,  7.40465362, 18.42431761,  9.385971  , 16.27514034,
        8.93253392, 22.25621959, 17.63016976, 16.44743142,  4.35665395,
       16.30375586, 10.36310439, 17.98948679, 18.41883769, 12.56445262,
       12.90007425, 12.02537802, 21.50978064, 17.51186359,  3.43654076])

In [20]:
lm.score(x_test,y_test)  # r^2 ajustado AUMENTARLO

#error DISMINUIRLO

0.8927130255676554

In [16]:
list(zip(sales_predict_2,y_test.tolist()))

[(20.830945471889915, 20.8),
 (11.53822356197336, 12.0),
 (7.522987068536044, 7.6),
 (16.97428844319716, 16.7),
 (21.709527625834212, 23.2),
 (21.115237646643873, 22.3),
 (15.63049875393719, 16.0),
 (24.82424957762576, 27.0),
 (15.451537280319817, 12.0),
 (6.426835020427181, 8.8),
 (11.432696569062395, 9.5),
 (8.765371979754642, 10.6),
 (13.102796585829138, 12.9),
 (17.19145121692625, 17.4),
 (8.032228403415525, 9.7),
 (21.250596096426655, 22.2),
 (15.25219741014943, 15.5),
 (15.092752781626643, 14.9),
 (10.599798545557656, 6.6),
 (9.772238679749254, 11.0),
 (8.679512706892616, 9.7),
 (7.404653624487613, 9.5),
 (18.424317608032073, 19.2),
 (9.38597100083728, 10.9),
 (16.275140343099693, 16.6),
 (8.932533922560097, 9.5),
 (22.25621958598099, 24.7),
 (17.630169761621858, 18.5),
 (16.447431421100283, 15.5),
 (4.356653953285454, 7.3),
 (16.303755857144765, 16.9),
 (10.363104389847267, 11.5),
 (17.989486794251228, 19.2),
 (18.418837693788408, 19.0),
 (12.564452619788417, 7.2),
 (12.90007425